### ISSUE TITLE
Help Regarding run.sh file

### ISSUE THREAD

**Issue by pankajsharma47** [centreborelli/mf2f#2]

**Comment by Valery-Dewil** [comment]
Hi, 
"Is it necessary for input to be .tiff format?" No, if iio is correctly installed, you can read and store images with format png, jpeg or tiff.

"tvl1flow.sh: line 15: parallel: command not found"
"compute_mask.sh: line 12: parallel: command not found" In order to speed up the computation of the flows and masks, we use parallel, you should install it.

"... ... /downs.tiff': No such file or directory"
"...  ... /downs_warp.tiff': No such file or directory"
"... ... /dwo.png': No such file or directory"
"... ... /mask_invalid_pixels.png': No such file or directory" All those files are created when you're computing the masks and remove later. Since you didn't manage to compute the masks, those files hadn't been created and the code failed to remove them.


"run.sh: line 83: python3.6: command not found"
"run.sh: line 87: python3.6: command not found"
"run.sh: line 92: python3.6: command not found"
"run.sh: line 97: python3.6: command not found"
"run.sh: line 102: python3.6: command not found"
"run.sh: line 75: python3.6: command not found" As explained in the README, we recommend you to use python3.6. If you want to use an other version of python, you can change the line 15 in the run.sh file:
PYTHON=python3.6

**Comment by pankajsharma47** [comment]
Thank you sir for such a great response. Can you please help me regarding parallel --bar command in .sh files? 
Actually it is giving error and tried using alternatives for this command but it failed.
Thank you.
